# Generated by Django 5.1.1 on 2024-10-05 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='add_to_cart_limit',
        ),
    ]
