# Generated by Django 5.1.1 on 2024-10-06 14:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_article_duration_article_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='article',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='article',
            name='places_count',
        ),
        migrations.RemoveField(
            model_name='article',
            name='views',
        ),
        migrations.AddField(
            model_name='cart',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='cart',
            name='duration',
            field=models.CharField(default=0, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='places_count',
            field=models.CharField(default=0, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='added_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='rating',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
