# Generated by Django 5.1.1 on 2024-10-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_article_duration_remove_article_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='max_articles_per_category',
            field=models.SmallIntegerField(default=3),
        ),
    ]
